### ISSUE TITLE
Attlasian Link 

### ISSUE THREAD

**Issue by AlekKras** [ph20/packer-blackarch#8]
`Building result on Atlas https://atlas.hashicorp.com/ph20/boxes/blackarch-core-x86_64`

The link doesn't work. However, managed to install it from app.vagrantup.com

**Comment by ph20** [comment]
Fixed https://github.com/ph20/packer-blackarch/commit/1ff2bb85f3bd3f29d601d44d1be404a174a32367
And new builds available
